# Below is the cleaning of lahore info file

In [ ]:
# import pandas as pd

# Read the CSV file
file_path = r'C:\Users\itw\Downloads\lahore csv\lahore_hotel_names.csv'
file_path1 = r'C:\Users\itw\Downloads\lahore csv\lahore_hotel_names_correct.csv'
df = pd.read_csv(file_path)

# Remove 'PKRA' from all values

# Concatenate columns 7, 8, and 9 together
df['hotel_price'] = df['hotel_price'].str.replace('PKRÂ ', '')

# Drop columns 7, 8, and 9
df.drop(df.columns[7:10], axis=1, inplace=True)

# Write the modified DataFrame back to the same CSV file
try:
    df.to_csv(file_path1, index=False)
    print("File successfully updated.")
except Exception as e:
    print("An error occurred while writing the file:", str(e))

In [10]:
df

,hotel_link,hotel_name,review_score,total_reviews,hotel_type,hotel_price,facilities
0,https://www.google.com/maps/place/Luxus+Grand+...,Luxus Grand Hotel,4.4,"6,298",5-star hotel,17.1K,Free parking
1,https://www.google.com/maps/place/Avari+Hotel+...,Avari Hotel Lahore,4.7,"25,664",5-star hotel,24.4K,Free parking
2,https://www.google.com/maps/place/Indigo+Heigh...,"Indigo Heights Hotel and Suites, Lahore",4.3,"5,645",Hotel,19.1K,Spa
3,https://www.google.com/maps/place/The+Nishat+H...,The Nishat Hotel,4.5,"13,189",5-star hotel,38.8K,Free parking
4,https://www.google.com/maps/place/Pearl+Contin...,"Pearl Continental Hotel,Lahore",4.4,"39,016",5-star hotel,34.3K,Spa
5,https://www.google.com/maps/place/Faletti%27s+...,Faletti's Hotel,4.3,"14,403",4-star hotel,23.2K,Free parking

# Below is the cleaning of islamabad hotels file

In [15]:
import pandas as pd

# Read the CSV file
file_path = r'C:\Users\itw\Downloads\islamabad csv\islamabad_hotel_names.csv'
file_path1 = r'C:\Users\itw\Downloads\islamabad csv\islamabad_hotel_names_corrected.csv'

df = pd.read_csv(file_path)

# Rename columns as per the requirement
df.columns = ['hotel_link', 'hotel_name', 'review_score', 'total_reviews', 'hotel_type', 'hotel_price']

# Keep only specific rows (1, 7, 5, 8, 10)
rows_to_keep = [1, 7, 5, 8, 10]
df = df.iloc[rows_to_keep]

# Remove '-' from values in the 'total_reviews' column
df['total_reviews'] = df['total_reviews'].str.replace('-', '')

# Remove 'PKRÂ ' from values in the 'hotel_price' column
df['hotel_price'] = df['hotel_price'].str.replace('PKRÂ ', '')

# Write the modified DataFrame back to the same CSV file
df.to_csv(file_path1, index=False)

In [16]:
df

,hotel_link,hotel_name,review_score,total_reviews,hotel_type,hotel_price
1,NaN,NaN,NaN,NaN,NaN,NaN
7,https://www.google.com/maps/place/The+108+Hote...,The 108 Hotel,4.7,(297),Hotel,PKR 31.4K
5,https://www.google.com/maps/place/Avari+Xpress...,Avari Xpress Residences Islamabad Hotel,4.6,"(3,096)",Hotel,PKR 22.9K
8,https://www.google.com/maps/place/Sintra+Hotel...,Sintra Hotel,4.4,(134),Hotel,PKR 17.1K
10,https://www.google.com/maps/place/Sheltons+Rez...,Sheltons Rezidor Islamabad,4.1,(920),Hotel,PKR 17.4K

# Cleaning of all review files of lahore

In [40]:
files = ['\Faletti hotel lahore reviews.csv', '\lahore avari hotels reviews.csv', '\luxus grand hotel lahore reviews.csv', '\Pearl Continental lahore Reviews.csv', '\The Nishat Hotel reviews lahore.csv']
path = r'C:\Users\itw\Downloads\lahore csv'
corrected_files = ['\Faletti hotel lahore reviews corrected.csv', '\lahore avari hotels reviews corrected.csv', '\luxus grand hotel lahore reviews corrected.csv', '\Pearl Continental lahore Reviews corrected.csv', '\The Nishat Hotel reviews lahore corrected.csv']

i=0
for file in files:
    file_path = f'{path}\\{file}'
    df = pd.read_csv(file_path)

# Remove first and third columns
    df.drop(df.columns[[0, 2]], axis=1, inplace=True)

    # Rename remaining columns as per the requirement
    df.columns = ['reviewer_name', 'review_time', 'review']
    
    file_path1 = f'{path}\\{corrected_files[i]}'
    # Write the modified DataFrame back to the same CSV file
    i = i + 1
    df.to_csv(file_path1, index=False)

In [41]:
df

,reviewer_name,review_time,review
0,M Anwar,2 weeks ago on,We made use of the restaurant buffet and my go...
1,afaq s,2 weeks ago on,Absolutely incredible experience! From the mom...
2,Faizan Ahmad,a month ago on,Fantastic encounter! A 5-star rating is unwort...
3,Usman Khan Y,4 weeks ago on,I have often stayed at Nishat Hotel and found ...
4,Mudasar Rasool,2 weeks ago on,A nice experience there. Staying at Nishat Hot...
...,...,...,...
58,All Around the world.,3 months ago on,The Nishat Hotel is amazing! They offer cozy r...
59,Shahzaib Khan,3 months ago on,The Nishat Hotel offers a luxurious experience...
60,Syed Ali Husnian Zaidii,2 weeks ago on,On Tuesday I getting hi-tea from cafe bistro i...
61,Muhammad Adil Naseem,2 months ago on,I recently stayed at The Nishat Hotel and was ...
62,Muhammad Hanif,2 weeks ago on,"A place where you feel like a home, The Nishat..."

# Cleaning all hotels of skp

In [44]:
files = ['\citi hotel skp reveiws.csv', '\sultan grand hotel reveiws skp.csv', '\Taj mahul hotel skp reveiws.csv']
path = r'C:\Users\itw\Downloads\skp csv'
corrected_files = ['\citi hotel skp reveiws corrected.csv', '\sultan grand hotel reveiws skp corrected.csv', '\Taj mahul hotel skp reveiws corrected.csv']

i=0
for file in files:
    file_path = f'{path}{file}'
    df = pd.read_csv(file_path)

# Remove first and third columns
    df.drop(df.columns[[0]], axis=1, inplace=True)

    # Rename remaining columns as per the requirement
    df.columns = ['reviewer_name', 'review_time', 'review']
    
    file_path1 = f'{path}{corrected_files[i]}'
    # Write the modified DataFrame back to the same CSV file
    i = i + 1
    df.to_csv(file_path1, index=False)

In [45]:
df

,reviewer_name,review_time,review
0,Arshad Mughal,a year ago,"Visited after checking the reviews history, fo..."
1,Rana Maaz,a year ago,The worst Restaurant Ever of my life\nVery tas...
2,Rafat Malik,a year ago,"Not a good experience, stayed there for three ..."
3,Khalid Muhammad,6 months ago,"A very nice addition in Sheikhupura,\nManageme..."
4,Nujba Zaidi,a month ago,Worst experience even the manger is illiterate...
5,SyeD BaDshah,a week ago,Good 😊\nNice 🙂\nPlace ❤️ …
6,Waqas Khalid,4 years ago,Best in taste and sitting area quite good as c...
7,Faisal Bhatti,5 years ago,"Soup, Drinks are the best...\nBut need more i..."
8,Asher Gill,3 months ago,It's a nice place for traditional foods
9,Kaleem Nizami,4 years ago,Awesome place and what tha amazing taste
10,Abbas Omar,2 weeks ago,Not a good experience.
11,عبد الرؤف گورایہ,a year ago,Very good Place & Excellent Service
12,Asif Toor,5 years ago,They Don't know what should be required for so...
13,zeeshan jutt28,a month ago,V good
14,Muhammad Naveed Malik,a year ago,"Worst ever experience of staying at Taj Mahal,..."
15,My Mob,4 years ago,Hello guys... I am going to give review on thi...
16,Naseer Ahmad,4 years ago,Its was GooD Experience... We have visited for...
17,Junel Solis,5 years ago,I've been to this restaurant a total of five t...
18,LORDS Gaming,3 years ago,We reached here at 9 pm. I called again and ag...
19,Sheeraz Khan,5 years ago,Above average but little expensive expensive c...
20,shakeel ahmad,2 years ago,"Slow service, non professional attitude, small..."
21,Zahid ashraf,4 years ago,Nice food..not so expensive... Interior is goo...
22,Hassan Gardezi,4 years ago,Taj Mahal interior is Good but they Usaly Serv...
23,Mansoor Elahi Choudhery,a year ago,Tight atmosphere.... Less parking average qual...
24,Faiza Jahanzaib,4 years ago,Tea taste boht acha tha. Resturent bsaaf suthr...
25,Saleem Akram,a year ago,Taste was normal and their service is not up t...
26,Sabahat Akram,3 years ago,Lunch was really good... Taste is really appre...
27,Zainab Munawar,2 years ago,"Amazing experience.... Fantastic taste , quick..."
28,itat hussain,2 years ago,I will not suggest anyone to visit here for bu...
29,hamid anwar,3 years ago,Unsatisfying service and room was not clean. I...
30,Umar 2070,a year ago,Taste is so good. Peaceful place for family
31,najaf abbas,2 years ago,Food taste is delicious.\nStaff is very profes...
32,M.W. Ashiq,3 years ago,Always have unique taste and good placement. r...
33,Dr H.Zia-ur-Rehman Bloach,4 years ago,Really good Taste of all foods at Taj Mahal. ....
34,usman haider,5 years ago,Its superb in environment and taste too..\nTo ...
35,Daniyal Cheema,4 years ago,Place was good they have a good sitting pkus p...
36,Khurram Shahzad,4 years ago,Good taste and fresh coking nice setting comfo...
37,Ali Muhammad,a month ago,Good
38,Hamza Aftab,4 years ago,The food was worst no taste no management even...
39,awaisarslan,5 years ago,Good high tea with lot of variety food item wi...
40,Imran Rafique,4 years ago,Good hotel rooms to stay in but rent is quite ...
41,Daud Ahmad,4 years ago,A good place for family functions
42,Urdu Adab Canada,4 years ago,Awesome cook there every person must be vist a...
43,Ali Naeem,4 years ago,The place have veary good sittinfg area f Nd f...
44,Farhan Abid,a month ago,Nice
45,Tariq Rasheed,2 months ago,Great
46,Mehran Dogar,4 years ago,Good quality food..with honorable staff
47,Syedahadia Islam,2 years ago,Its taste is delicious and sitting plan also good
48,Zafar Hussain,2 months ago,Awesome
49,Brain Box,4 years ago,Taste of food was average.But severing way was...
50,ASAD TAHIR,4 years ago,Service is not good . But food is tasty.
51,fahad waheed,3 years ago,"Extremely pathetic food, ordered Mutton karahi..."
52,Al-barkat Glass,5 years ago,Very good place in skp for dinner lunch partie...
53,Zain Ali,4 years ago,food was just ok. dining hall was acceptable b...
54,Suhaib Gujjar,3 years ago,Taste n Environment is very good. Recommended
55,Sheeraz Raja,4 years ago,"Delicious Food, eye catching rooftop, wide eve..."
56,Mian Muhammad Salman Ali,3 years ago,Its a good thing to share knowledge and i form...
57,Muhammad Adeel,4 years ago,Nice & good taste of food & quite nice sitting...
58,Azeem Ahmad,2 years ago,Taste is good. Dealing is also well
59,nouman asif,3 years ago,Very bad service. They are lier Greedy. We wil...

# Cleaning all reviews of karachi

In [49]:
files = ['\Avari Tower Karachi Reveiws.csv', '\Beach Luxury hotel karachi reveiws.csv', '\Karachi Marriott hotel karachi reviews.csv', '\Movenpick Karachi hotel reviews.csv', '\Pearl Continental Hotel Karachi Reveiws.csv']
path = r'C:\Users\itw\Downloads\karachi csv'
corrected_files = ['\Avari Tower Karachi Reveiws corrected.csv', '\Beach Luxury hotel karachi reveiws corrected.csv', '\Karachi Marriott hotel karachi reviews corrected.csv', '\Movenpick Karachi hotel reviews corrected.csv', '\Pearl Continental Hotel Karachi Reveiws corrected.csv']

i=0
for file in files:
    file_path = f'{path}{file}'
    df = pd.read_csv(file_path)

# Remove first and third columns
    df.drop(df.columns[[0, 2]], axis=1, inplace=True)

    # Rename remaining columns as per the requirement
    df.columns = ['reviewer_name', 'review_time', 'review']
    
    file_path1 = f'{path}{corrected_files[i]}'
    # Write the modified DataFrame back to the same CSV file
    i = i + 1
    df.to_csv(file_path1, index=False)

In [50]:
df

,reviewer_name,review_time,review
0,Abid Hussain,2 weeks ago on,I recently had the pleasure of staying at your...
1,Tauqeer Mirza,a month ago on,My stay at Pearl Continental Hotel Karachi was...
2,Ameen Ullah,2 weeks ago on,"As one of the top accommodations in the city, ..."
3,Ali Masood,a month ago on,Our organization recently hosted a four-day ev...
4,Syed Muhammad ABBAS,3 months ago on,Surpassed all expectations with its opulent ac...
...,...,...,...
78,Kazim Ali,3 months ago on,I recently stayed at the Pearl Continental Kar...
79,Rafaqat Ali,3 weeks ago on,PC Karachi ambiance is attractive.cleanliness ...
80,USAMA QURESHI,3 months ago on,Experience luxury at its finest at the Golden ...
81,Muhammad Qasim,3 months ago on,Pearl Continental Hotel Karachi delivers outst...
82,Scribed 2,3 months ago on,I recently had a great stay at Pearl Continent...

# Cleaning of all hotels of islamabad

In [51]:
files = ['\Avari Xpress Residence islamabad reveiws.csv', '\Gateway Islamabad hotel reveiws.csv', '\Grand Islamabad hotel reviews.csv', '\margalla hotel islamabad reveiws.csv', '\Serena hotel islamabad reveiws.csv']
path = r'C:\Users\itw\Downloads\islamabad csv'
corrected_files = ['\Avari Xpress Residence islamabad reveiws corrected.csv', '\Gateway Islamabad hotel reveiws corrected.csv', '\Grand Islamabad hotel reviews corrected.csv', '\margalla hotel islamabad reveiws corrected.csv', '\Serena hotel islamabad reveiws corrected.csv']

i=0
for file in files:
    file_path = f'{path}{file}'
    df = pd.read_csv(file_path)

# Remove first and third columns
    df.drop(df.columns[[0, 2]], axis=1, inplace=True)

    # Rename remaining columns as per the requirement
    df.columns = ['reviewer_name', 'review_time', 'review']
    
    file_path1 = f'{path}{corrected_files[i]}'
    # Write the modified DataFrame back to the same CSV file
    i = i + 1
    df.to_csv(file_path1, index=False)

In [52]:
df

,reviewer_name,review_time,review
0,M. Kaan OZASLAN,a week ago on,Firstly the staff was very kind and profession...
1,faisal ali,a month ago on,My recent stay at this hotel in Islamabad was ...
2,Muhammad Sheharyar Baig,a month ago on,"The hotel is located in the heart of the city,..."
3,Ahmed Nadeem,a month ago on,I recently had a visit to Islamabad for a frie...
4,Muhammad Rashid,a month ago on,"Nestled in the heart of Islamabad, Sarina Hote..."
...,...,...,...
75,Hamza Badar,a month ago on,The accommodations at Serena Hotel were exquis...
76,zainab imad,a month ago on,My two-day stay at Serena Hotel Islamabad was ...
77,Salal Khan,a month ago on,"- ""Extremely well maintained Hotel with a touc..."
78,Aimen S,a month ago on,Had delightful lunch at Rakaposhi with friends...
79,Aleem Manzoor,a month ago on,Exceptional stay at this hotel! From the warm ...